In [1]:
from keras.datasets import mnist
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


Using TensorFlow backend.


In [2]:
(train_data, train_labels), (test_data, test_labels) = mnist.load_data()

In [3]:
f'train data shape:{train_data.shape} and labels shape: {train_labels.shape}'

'train data shape:(60000, 28, 28) and labels shape: (60000,)'

In [4]:
y = pd.Series(train_labels).astype('int').astype('category')
X = pd.DataFrame(train_data[0])

In [5]:
X_values = pd.Series(X.values.ravel())
print(f'min: {X_values.min()}')
print(f'min: {X_values.max()}')
print(f'max: {X_values.mean()}')
print(f'mean: {X_values.median()}')


min: 0
min: 255
max: 35.108418367346935
mean: 0.0


In [6]:
print('The distribution of each image:')
y.value_counts(normalize=True)

The distribution of each image:


1    0.112367
7    0.104417
3    0.102183
2    0.099300
9    0.099150
0    0.098717
6    0.098633
8    0.097517
4    0.097367
5    0.090350
dtype: float64

In [7]:
np.set_printoptions(linewidth = 150)#default = 75

In [8]:
print(train_data[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 182 247 241   0   

In [9]:
# mean of all train_data
plt.imshow(train_data.mean(axis=0))

In [10]:
# mean of all train_data with label of 5
fives = list(np.nonzero(train_labels == 5)[0]) #indexes of 5
fives_arrays = [train_data[i] for i in range(len(train_data)) if i in fives]
fives_arrays = np.array(fives_arrays)
plt.imshow(fives_arrays.mean(axis=0)) 